# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "age_ranges", :force => true do |t|
    t.column "low",  :integer, :null => false
    t.column "high", :integer, :null => false
  end

  create_table "events", :force => true do |t|
    t.column "year",               :integer,                  :null => false
    t.column "location",           :string,   :default => "", :null => false
    t.column "registration_cost",  :integer,  :default => 0,  :null => false
    t.column "registration_count", :integer,  :default => 0,  :null => false
    t.column "max_seats",          :integer,  :default => 0,  :null => false
    t.column "lock_version",       :integer,  :default => 0,  :null => false
    t.column "created_at",         :datetime,                 :null => false
    t.column "updated_at",         :datetime,                 :null => false
    t.column "start_date",         :datetime
    t.column "end_date",           :datetime
  end

  create_table "registrations", :force => true do |t|
    t.column "address1",     :string,                :default => "", :null => false
    t.column "address2",     :string
    t.column "city",         :string,                :default => "", :null => false
    t.column "state",        :string,   :limit => 2
    t.column "phone",        :string,                :default => "", :null => false
    t.column "first_name",   :string,                :default => "", :null => false
    t.column "last_name",    :string,                :default => "", :null => false
    t.column "middle_name",  :string
    t.column "age_range_id", :integer,               :default => 0,  :null => false
    t.column "created_at",   :datetime,                              :null => false
    t.column "updated_at",   :datetime,                              :null => false
    t.column "lock_version", :integer,               :default => 0,  :null => false
    t.column "event_id",     :integer
    t.column "amount_paid",  :integer,               :default => 0,  :null => false
    t.column "amount_owed",  :integer,               :default => 0,  :null => false
    t.column "user_id",      :integer,                               :null => false
    t.column "gender",       :string,   :limit => 1, :default => "", :null => false
    t.column "zip_code",     :string
  end

  create_table "users", :force => true do |t|
    t.column "email",           :string,   :limit => 128, :default => "",    :null => false
    t.column "hashed_password", :string,                  :default => "",    :null => false
    t.column "salt",            :string,                  :default => "",    :null => false
    t.column "created_at",      :datetime,                                   :null => false
    t.column "last_visit",      :datetime,                                   :null => false
    t.column "admin",           :boolean,                 :default => false, :null => false
    t.column "lock_version",    :integer,                 :default => 0,     :null => false
    t.column "activated",       :boolean,                 :default => false, :null => false
  end

end
